import type { AdminCustomOrder } from '../../lib/db/customOrders';

const now = new Date('2026-02-26T12:00:00.000Z');
const isoDaysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
const customImage = (index: number) => `/demo-seed/custom-orders/co-${String(index).padStart(2, '0')}.svg`;

export const seedAdminCustomOrders: AdminCustomOrder[] = [
  {
    id: 'seed_custom_order_001',
    displayCustomOrderId: 'CO-26-001',
    customerName: 'Leah Carter',
    customerEmail: 'leah.carter@example.com',
    description: 'Custom pet portrait (digital) of a golden retriever in wildflower field colors.',
    imageUrl: customImage(1),
    imageId: null,
    imageStorageKey: null,
    amount: 8500,
    shippingCents: 0,
    showOnSoldProducts: false,
    status: 'pending',
    paymentLink: 'https://checkout.stripe.com/c/pay/demo_co_001',
    createdAt: isoDaysAgo(1),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_002',
    displayCustomOrderId: 'CO-26-002',
    customerName: 'Mason Hill',
    customerEmail: 'mason.hill@example.com',
    description: 'Wedding signage set including welcome sign, bar menu, and 10 table numbers.',
    imageUrl: customImage(2),
    imageId: null,
    imageStorageKey: null,
    amount: 18400,
    shippingCents: 1400,
    showOnSoldProducts: true,
    status: 'paid',
    paymentLink: 'https://checkout.stripe.com/c/pay/demo_co_002',
    createdAt: isoDaysAgo(2),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_003',
    displayCustomOrderId: 'CO-26-003',
    customerName: 'Arianna Price',
    customerEmail: 'arianna.price@example.com',
    description: 'Embroidered denim jacket with custom floral back panel and sleeve initials.',
    imageUrl: customImage(3),
    imageId: null,
    imageStorageKey: null,
    amount: 12900,
    shippingCents: 950,
    showOnSoldProducts: false,
    status: 'pending',
    paymentLink: null,
    createdAt: isoDaysAgo(3),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_004',
    displayCustomOrderId: 'CO-26-004',
    customerName: 'Benjamin Ross',
    customerEmail: 'benjamin.ross@example.com',
    description: 'Logo illustration package for coffee shop: primary lockup, icon, and alternate mark.',
    imageUrl: customImage(4),
    imageId: null,
    imageStorageKey: null,
    amount: 22500,
    shippingCents: 0,
    showOnSoldProducts: false,
    status: 'pending',
    paymentLink: 'https://checkout.stripe.com/c/pay/demo_co_004',
    createdAt: isoDaysAgo(4),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_005',
    displayCustomOrderId: 'CO-26-005',
    customerName: 'Nora Diaz',
    customerEmail: 'nora.diaz@example.com',
    description: 'Crocheted plush commission for two bees and one matching sunflower plush.',
    imageUrl: customImage(5),
    imageId: null,
    imageStorageKey: null,
    amount: 9800,
    shippingCents: 700,
    showOnSoldProducts: true,
    status: 'paid',
    paymentLink: 'https://checkout.stripe.com/c/pay/demo_co_005',
    createdAt: isoDaysAgo(5),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_006',
    displayCustomOrderId: 'CO-26-006',
    customerName: 'Caleb Ward',
    customerEmail: 'caleb.ward@example.com',
    description: 'Hand-painted skateboard deck with mountain gradient and gold linework.',
    imageUrl: customImage(6),
    imageId: null,
    imageStorageKey: null,
    amount: 14700,
    shippingCents: 1200,
    showOnSoldProducts: false,
    status: 'pending',
    paymentLink: null,
    createdAt: isoDaysAgo(6),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_007',
    displayCustomOrderId: 'CO-26-007',
    customerName: 'Sienna Knight',
    customerEmail: 'sienna.knight@example.com',
    description: 'Ceramic mug set of four with hand-painted initials and gift box packaging.',
    imageUrl: customImage(7),
    imageId: null,
    imageStorageKey: null,
    amount: 16400,
    shippingCents: 1600,
    showOnSoldProducts: true,
    status: 'paid',
    paymentLink: 'https://checkout.stripe.com/c/pay/demo_co_007',
    createdAt: isoDaysAgo(8),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_008',
    displayCustomOrderId: 'CO-26-008',
    customerName: 'Daniel Park',
    customerEmail: 'daniel.park@example.com',
    description: 'Batch order of 80 leather keychains with debossed conference logo.',
    imageUrl: customImage(8),
    imageId: null,
    imageStorageKey: null,
    amount: 30200,
    shippingCents: 1800,
    showOnSoldProducts: false,
    status: 'pending',
    paymentLink: 'https://checkout.stripe.com/c/pay/demo_co_008',
    createdAt: isoDaysAgo(9),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_009',
    displayCustomOrderId: 'CO-26-009',
    customerName: 'Grace Turner',
    customerEmail: 'grace.turner@example.com',
    description: 'Custom stationery suite: save-the-date card, invitation, and details insert.',
    imageUrl: customImage(9),
    imageId: null,
    imageStorageKey: null,
    amount: 13600,
    shippingCents: 900,
    showOnSoldProducts: false,
    status: 'pending',
    paymentLink: null,
    createdAt: isoDaysAgo(10),
    archived: false,
    archivedAt: null,
  },
  {
    id: 'seed_custom_order_010',
    displayCustomOrderId: 'CO-26-010',
    customerName: 'Henry Collins',
    customerEmail: 'henry.collins@example.com',
    description: 'Custom candle favor set for 60 guests with personalized labels and scent blend.',
    imageUrl: customImage(10),
    imageId: null,
    imageStorageKey: null,
    amount: 26800,
    shippingCents: 2000,
    showOnSoldProducts: true,
    status: 'paid',
    paymentLink: 'https://checkout.stripe.com/c/pay/demo_co_010',
    createdAt: isoDaysAgo(12),
    archived: false,
    archivedAt: null,
  },
];
