import type { AdminOrder } from '../../lib/db/orders';

const now = new Date('2026-02-26T12:00:00.000Z');
const isoHoursAgo = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
const productImage = (index: number) => `/demo-assets/products/product-${String(index).padStart(2, '0')}.svg`;

export const seedAdminOrders: AdminOrder[] = [
  {
    id: 'seed_order_001',
    displayOrderId: 'MV-1001',
    createdAt: isoHoursAgo(3),
    totalCents: 12670,
    amountTotalCents: 12670,
    amountSubtotalCents: 10900,
    amountShippingCents: 900,
    amountTaxCents: 870,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'olivia.martin@example.com',
    shippingName: 'Olivia Martin',
    customerName: 'Olivia Martin',
    shippingAddress: {
      name: 'Olivia Martin',
      line1: '118 Harbor Lane',
      line2: '',
      city: 'Annapolis',
      state: 'MD',
      postal_code: '21401',
      country: 'US',
      phone: '+1 410-555-0101',
    },
    cardLast4: '4242',
    cardBrand: 'visa',
    paymentMethodType: 'card',
    paymentMethodLabel: 'Visa ending in 4242',
    shippingCents: 900,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: false,
    seenAt: null,
    items: [
      {
        productId: 'seed_prod_001',
        productName: 'Hand-Printed Studio Tee',
        quantity: 2,
        priceCents: 3200,
        imageUrl: productImage(1),
      },
      {
        productId: 'seed_prod_007',
        productName: 'Vinyl Sticker Pack',
        quantity: 1,
        priceCents: 900,
        imageUrl: productImage(7),
      },
      {
        productId: 'seed_prod_006',
        productName: 'Enamel Pin - Moon Cat',
        quantity: 3,
        priceCents: 1200,
        imageUrl: productImage(6),
      },
    ],
  },
  {
    id: 'seed_order_002',
    displayOrderId: 'MV-1002',
    createdAt: isoHoursAgo(8),
    totalCents: 13710,
    amountTotalCents: 13710,
    amountSubtotalCents: 15000,
    amountShippingCents: 0,
    amountTaxCents: 960,
    amountDiscountCents: 2250,
    currency: 'usd',
    customerEmail: 'ethan.reed@example.com',
    shippingName: 'Ethan Reed',
    customerName: 'Ethan Reed',
    shippingAddress: {
      name: 'Ethan Reed',
      line1: '22 Riverwalk Dr',
      line2: 'Apt 4B',
      city: 'Wilmington',
      state: 'NC',
      postal_code: '28401',
      country: 'US',
      phone: '+1 910-555-0142',
    },
    shippingCents: 0,
    promoCode: 'MAKER15',
    promoPercentOff: 15,
    promoFreeShipping: true,
    promoSource: 'promo_code',
    isSeen: false,
    seenAt: null,
    items: [
      {
        productId: 'seed_prod_016',
        productName: 'Wedding Welcome Sign Bundle',
        quantity: 1,
        priceCents: 9800,
        imageUrl: productImage(16),
      },
      {
        productId: 'seed_prod_015',
        productName: 'Letterpress Stationery Set',
        quantity: 2,
        priceCents: 2600,
        imageUrl: productImage(15),
      },
    ],
  },
  {
    id: 'seed_order_003',
    displayOrderId: 'MV-1003',
    createdAt: isoHoursAgo(11),
    totalCents: 14180,
    amountTotalCents: 14180,
    amountSubtotalCents: 12000,
    amountShippingCents: 1400,
    amountTaxCents: 780,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'harper.lynch@example.com',
    shippingName: 'Harper Lynch',
    customerName: 'Harper Lynch',
    shippingAddress: {
      name: 'Harper Lynch',
      line1: '77 Seaside Ave',
      line2: '',
      city: 'Charleston',
      state: 'SC',
      postal_code: '29401',
      country: 'US',
      phone: '+1 843-555-0178',
    },
    shippingCents: 1400,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(10),
    items: [
      {
        productId: 'seed_prod_004',
        productName: 'Ceramic Speckle Mug',
        quantity: 2,
        priceCents: 3600,
        imageUrl: productImage(4),
      },
      {
        productId: 'seed_prod_003',
        productName: 'Small-Batch Soy Candle - Sage',
        quantity: 2,
        priceCents: 2400,
        imageUrl: productImage(3),
      },
    ],
  },
  {
    id: 'seed_order_004',
    displayOrderId: 'MV-1004',
    createdAt: isoHoursAgo(15),
    totalCents: 26250,
    amountTotalCents: 26250,
    amountSubtotalCents: 22600,
    amountShippingCents: 2200,
    amountTaxCents: 1450,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'amelia.taylor@example.com',
    shippingName: 'Amelia Taylor',
    customerName: 'Amelia Taylor',
    shippingAddress: {
      name: 'Amelia Taylor',
      line1: '9 Sunrise Point',
      line2: '',
      city: 'Savannah',
      state: 'GA',
      postal_code: '31401',
      country: 'US',
      phone: '+1 912-555-0199',
    },
    shippingCents: 2200,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(14),
    items: [
      {
        productId: 'seed_prod_014',
        productName: 'Maple Cutting Board - Mini',
        quantity: 2,
        priceCents: 5200,
        imageUrl: productImage(14),
      },
      {
        productId: 'seed_prod_013',
        productName: 'Walnut Coaster Set',
        quantity: 2,
        priceCents: 3800,
        imageUrl: productImage(13),
      },
      {
        productId: 'seed_prod_011',
        productName: 'Leather Card Wallet',
        quantity: 1,
        priceCents: 4600,
        imageUrl: productImage(11),
      },
    ],
  },
  {
    id: 'seed_order_005',
    displayOrderId: 'MV-1005',
    createdAt: isoHoursAgo(20),
    totalCents: 3540,
    amountTotalCents: 3540,
    amountSubtotalCents: 3000,
    amountShippingCents: 350,
    amountTaxCents: 190,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'noah.hayes@example.com',
    shippingName: 'Noah Hayes',
    customerName: 'Noah Hayes',
    shippingAddress: {
      name: 'Noah Hayes',
      line1: '1402 Bayview Ct',
      line2: '',
      city: 'Tampa',
      state: 'FL',
      postal_code: '33602',
      country: 'US',
      phone: '+1 813-555-0110',
    },
    shippingCents: 350,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(18),
    items: [
      {
        productId: 'seed_prod_007',
        productName: 'Vinyl Sticker Pack',
        quantity: 2,
        priceCents: 900,
        imageUrl: productImage(7),
      },
      {
        productId: 'seed_prod_006',
        productName: 'Enamel Pin - Moon Cat',
        quantity: 1,
        priceCents: 1200,
        imageUrl: productImage(6),
      },
    ],
  },
  {
    id: 'seed_order_006',
    displayOrderId: 'MV-1006',
    createdAt: isoHoursAgo(24),
    totalCents: 13420,
    amountTotalCents: 13420,
    amountSubtotalCents: 12400,
    amountShippingCents: 850,
    amountTaxCents: 790,
    amountDiscountCents: 620,
    currency: 'usd',
    customerEmail: 'ava.king@example.com',
    shippingName: 'Ava King',
    customerName: 'Ava King',
    shippingAddress: {
      name: 'Ava King',
      line1: '19 Pelican Way',
      line2: '',
      city: 'Newport',
      state: 'RI',
      postal_code: '02840',
      country: 'US',
      phone: '+1 401-555-0107',
    },
    shippingCents: 850,
    promoCode: 'WELCOME5',
    promoPercentOff: 5,
    promoFreeShipping: false,
    promoSource: 'promo_code',
    isSeen: true,
    seenAt: isoHoursAgo(22),
    items: [
      {
        productId: 'seed_prod_005',
        productName: 'Botanical Art Print 8x10',
        quantity: 3,
        priceCents: 1800,
        imageUrl: productImage(5),
      },
      {
        productId: 'seed_prod_015',
        productName: 'Letterpress Stationery Set',
        quantity: 1,
        priceCents: 2600,
        imageUrl: productImage(15),
      },
      {
        productId: 'seed_prod_012',
        productName: 'Leather Keychain Set',
        quantity: 2,
        priceCents: 2200,
        imageUrl: productImage(12),
      },
    ],
  },
  {
    id: 'seed_order_007',
    displayOrderId: 'MV-1007',
    createdAt: isoHoursAgo(28),
    totalCents: 8100,
    amountTotalCents: 8100,
    amountSubtotalCents: 7500,
    amountShippingCents: 0,
    amountTaxCents: 600,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'liam.green@example.com',
    shippingName: 'Liam Green',
    customerName: 'Liam Green',
    shippingAddress: {
      name: 'Liam Green',
      line1: '8 Driftwood Ln',
      line2: '',
      city: 'Mobile',
      state: 'AL',
      postal_code: '36602',
      country: 'US',
      phone: '+1 251-555-0155',
    },
    shippingCents: 0,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: true,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(27),
    items: [
      {
        productId: 'seed_prod_017',
        productName: 'Custom Pet Portrait Digital',
        quantity: 1,
        priceCents: 7500,
        imageUrl: productImage(17),
      },
    ],
  },
  {
    id: 'seed_order_008',
    displayOrderId: 'MV-1008',
    createdAt: isoHoursAgo(34),
    totalCents: 13080,
    amountTotalCents: 13080,
    amountSubtotalCents: 11400,
    amountShippingCents: 950,
    amountTaxCents: 730,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'mia.bennett@example.com',
    shippingName: 'Mia Bennett',
    customerName: 'Mia Bennett',
    shippingAddress: {
      name: 'Mia Bennett',
      line1: '404 Shoreline Blvd',
      line2: '',
      city: 'Galveston',
      state: 'TX',
      postal_code: '77550',
      country: 'US',
      phone: '+1 409-555-0119',
    },
    shippingCents: 950,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(33),
    items: [
      {
        productId: 'seed_prod_001',
        productName: 'Hand-Printed Studio Tee',
        quantity: 1,
        priceCents: 3200,
        imageUrl: productImage(1),
      },
      {
        productId: 'seed_prod_002',
        productName: 'Embroidered Canvas Hat',
        quantity: 1,
        priceCents: 2800,
        imageUrl: productImage(2),
      },
      {
        productId: 'seed_prod_009',
        productName: 'Crochet Beanie - Oatmeal',
        quantity: 1,
        priceCents: 3000,
        imageUrl: productImage(9),
      },
      {
        productId: 'seed_prod_006',
        productName: 'Enamel Pin - Moon Cat',
        quantity: 2,
        priceCents: 1200,
        imageUrl: productImage(6),
      },
    ],
  },
  {
    id: 'seed_order_009',
    displayOrderId: 'MV-1009',
    createdAt: isoHoursAgo(39),
    totalCents: 12830,
    amountTotalCents: 12830,
    amountSubtotalCents: 11400,
    amountShippingCents: 700,
    amountTaxCents: 730,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'lucas.wright@example.com',
    shippingName: 'Lucas Wright',
    customerName: 'Lucas Wright',
    shippingAddress: {
      name: 'Lucas Wright',
      line1: '520 Marina Dr',
      line2: '',
      city: 'Norfolk',
      state: 'VA',
      postal_code: '23510',
      country: 'US',
      phone: '+1 757-555-0182',
    },
    shippingCents: 700,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(37),
    items: [
      {
        productId: 'seed_prod_008',
        productName: 'Sterling Fern Pendant',
        quantity: 1,
        priceCents: 4200,
        imageUrl: productImage(8),
      },
      {
        productId: 'seed_prod_003',
        productName: 'Small-Batch Soy Candle - Sage',
        quantity: 3,
        priceCents: 2400,
        imageUrl: productImage(3),
      },
    ],
  },
  {
    id: 'seed_order_010',
    displayOrderId: 'MV-1010',
    createdAt: isoHoursAgo(46),
    totalCents: 14130,
    amountTotalCents: 14130,
    amountSubtotalCents: 11600,
    amountShippingCents: 1600,
    amountTaxCents: 930,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'ella.foster@example.com',
    shippingName: 'Ella Foster',
    customerName: 'Ella Foster',
    shippingAddress: {
      name: 'Ella Foster',
      line1: '16 Salt Marsh Rd',
      line2: '',
      city: 'Portland',
      state: 'ME',
      postal_code: '04101',
      country: 'US',
      phone: '+1 207-555-0108',
    },
    shippingCents: 1600,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(44),
    items: [
      {
        productId: 'seed_prod_016',
        productName: 'Wedding Welcome Sign Bundle',
        quantity: 1,
        priceCents: 9800,
        imageUrl: productImage(16),
      },
      {
        productId: 'seed_prod_005',
        productName: 'Botanical Art Print 8x10',
        quantity: 1,
        priceCents: 1800,
        imageUrl: productImage(5),
      },
    ],
  },
  {
    id: 'seed_order_011',
    displayOrderId: 'MV-1011',
    createdAt: isoHoursAgo(54),
    totalCents: 11330,
    amountTotalCents: 11330,
    amountSubtotalCents: 9800,
    amountShippingCents: 900,
    amountTaxCents: 630,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'jackson.moore@example.com',
    shippingName: 'Jackson Moore',
    customerName: 'Jackson Moore',
    shippingAddress: {
      name: 'Jackson Moore',
      line1: '72 Wavecrest Ct',
      line2: '',
      city: 'San Diego',
      state: 'CA',
      postal_code: '92101',
      country: 'US',
      phone: '+1 619-555-0135',
    },
    shippingCents: 900,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(53),
    items: [
      {
        productId: 'seed_prod_010',
        productName: 'Crochet Plush Bee',
        quantity: 1,
        priceCents: 3400,
        imageUrl: productImage(10),
      },
      {
        productId: 'seed_prod_019',
        productName: 'Clay Plant Marker Set',
        quantity: 2,
        priceCents: 2000,
        imageUrl: productImage(19),
      },
      {
        productId: 'seed_prod_003',
        productName: 'Small-Batch Soy Candle - Sage',
        quantity: 1,
        priceCents: 2400,
        imageUrl: productImage(3),
      },
    ],
  },
  {
    id: 'seed_order_012',
    displayOrderId: 'MV-1012',
    createdAt: isoHoursAgo(63),
    totalCents: 20730,
    amountTotalCents: 20730,
    amountSubtotalCents: 17800,
    amountShippingCents: 1800,
    amountTaxCents: 1130,
    amountDiscountCents: 0,
    currency: 'usd',
    customerEmail: 'sophia.brooks@example.com',
    shippingName: 'Sophia Brooks',
    customerName: 'Sophia Brooks',
    shippingAddress: {
      name: 'Sophia Brooks',
      line1: '305 Lighthouse Row',
      line2: '',
      city: 'Cape May',
      state: 'NJ',
      postal_code: '08204',
      country: 'US',
      phone: '+1 609-555-0166',
    },
    shippingCents: 1800,
    promoCode: null,
    promoPercentOff: null,
    promoFreeShipping: false,
    promoSource: null,
    isSeen: true,
    seenAt: isoHoursAgo(62),
    items: [
      {
        productId: 'seed_prod_018',
        productName: 'Hand-Painted Skateboard Deck',
        quantity: 1,
        priceCents: 11000,
        imageUrl: productImage(18),
      },
      {
        productId: 'seed_prod_020',
        productName: 'Macrame Wall Hanging',
        quantity: 1,
        priceCents: 6800,
        imageUrl: productImage(20),
      },
    ],
  },
];

