import type { Product } from '../../lib/types';

type ProductSeedRow = {
  id: string;
  name: string;
  description: string;
  type: string;
  category: string;
  priceCents: number;
  quantityAvailable: number;
  oneoff: boolean;
  image: string;
};

const rows: ProductSeedRow[] = [
  {
    id: 'seed_prod_001',
    name: 'Hand-Printed Studio Tee',
    description: 'Soft ring-spun cotton tee with hand-pulled studio print.',
    type: 'Apparel',
    category: 'Apparel',
    priceCents: 3200,
    quantityAvailable: 18,
    oneoff: false,
    image: '/demo-seed/products/prod-01.svg',
  },
  {
    id: 'seed_prod_002',
    name: 'Embroidered Canvas Hat',
    description: 'Low-profile canvas hat with stitched maker mark.',
    type: 'Apparel',
    category: 'Apparel',
    priceCents: 2800,
    quantityAvailable: 22,
    oneoff: false,
    image: '/demo-seed/products/prod-02.svg',
  },
  {
    id: 'seed_prod_003',
    name: 'Small-Batch Soy Candle - Sage',
    description: '8oz soy candle with cotton wick and recyclable jar.',
    type: 'Candles',
    category: 'Candles',
    priceCents: 2400,
    quantityAvailable: 35,
    oneoff: false,
    image: '/demo-seed/products/prod-03.svg',
  },
  {
    id: 'seed_prod_004',
    name: 'Ceramic Speckle Mug',
    description: 'Wheel-thrown ceramic mug with matte glaze finish.',
    type: 'Ceramics',
    category: 'Ceramics',
    priceCents: 3600,
    quantityAvailable: 12,
    oneoff: false,
    image: '/demo-seed/products/prod-04.svg',
  },
  {
    id: 'seed_prod_005',
    name: 'Botanical Art Print 8x10',
    description: 'Archival matte print from original hand-inked drawing.',
    type: 'Art Prints',
    category: 'Art Prints',
    priceCents: 1800,
    quantityAvailable: 40,
    oneoff: false,
    image: '/demo-seed/products/prod-05.svg',
  },
  {
    id: 'seed_prod_006',
    name: 'Enamel Pin - Moon Cat',
    description: 'Hard enamel lapel pin with black nickel plating.',
    type: 'Merch',
    category: 'Merch',
    priceCents: 1200,
    quantityAvailable: 70,
    oneoff: false,
    image: '/demo-seed/products/prod-06.svg',
  },
  {
    id: 'seed_prod_007',
    name: 'Vinyl Sticker Pack',
    description: 'Weatherproof sticker pack with six original designs.',
    type: 'Merch',
    category: 'Merch',
    priceCents: 900,
    quantityAvailable: 120,
    oneoff: false,
    image: '/demo-seed/products/prod-07.svg',
  },
  {
    id: 'seed_prod_008',
    name: 'Sterling Fern Pendant',
    description: 'Hand-sawn sterling pendant on an 18 inch chain.',
    type: 'Jewelry',
    category: 'Jewelry',
    priceCents: 4200,
    quantityAvailable: 8,
    oneoff: false,
    image: '/demo-seed/products/prod-08.svg',
  },
  {
    id: 'seed_prod_009',
    name: 'Crochet Beanie - Oatmeal',
    description: 'Soft acrylic-wool blend beanie, one size fits most.',
    type: 'Crochet',
    category: 'Crochet',
    priceCents: 3000,
    quantityAvailable: 14,
    oneoff: false,
    image: '/demo-seed/products/prod-09.svg',
  },
  {
    id: 'seed_prod_010',
    name: 'Crochet Plush Bee',
    description: 'Hand-crocheted plush bee with safety eyes.',
    type: 'Crochet',
    category: 'Crochet',
    priceCents: 3400,
    quantityAvailable: 10,
    oneoff: false,
    image: '/demo-seed/products/prod-10.svg',
  },
  {
    id: 'seed_prod_011',
    name: 'Leather Card Wallet',
    description: 'Vegetable-tanned leather wallet with edge burnish.',
    type: 'Leather Goods',
    category: 'Leather Goods',
    priceCents: 4600,
    quantityAvailable: 9,
    oneoff: false,
    image: '/demo-seed/products/prod-11.svg',
  },
  {
    id: 'seed_prod_012',
    name: 'Leather Keychain Set',
    description: 'Set of two stamped leather keychains with brass hardware.',
    type: 'Leather Goods',
    category: 'Leather Goods',
    priceCents: 2200,
    quantityAvailable: 26,
    oneoff: false,
    image: '/demo-seed/products/prod-12.svg',
  },
  {
    id: 'seed_prod_013',
    name: 'Walnut Coaster Set',
    description: 'Set of four hand-oiled walnut coasters.',
    type: 'Wood Goods',
    category: 'Wood Goods',
    priceCents: 3800,
    quantityAvailable: 11,
    oneoff: false,
    image: '/demo-seed/products/prod-13.svg',
  },
  {
    id: 'seed_prod_014',
    name: 'Maple Cutting Board - Mini',
    description: 'Small maple prep board with chamfered edge.',
    type: 'Wood Goods',
    category: 'Wood Goods',
    priceCents: 5200,
    quantityAvailable: 7,
    oneoff: false,
    image: '/demo-seed/products/prod-14.svg',
  },
  {
    id: 'seed_prod_015',
    name: 'Letterpress Stationery Set',
    description: 'Twelve letterpress cards with kraft envelopes.',
    type: 'Stationery',
    category: 'Stationery',
    priceCents: 2600,
    quantityAvailable: 30,
    oneoff: false,
    image: '/demo-seed/products/prod-15.svg',
  },
  {
    id: 'seed_prod_016',
    name: 'Wedding Welcome Sign Bundle',
    description: 'Painted welcome sign with matching table number cards.',
    type: 'Wedding',
    category: 'Wedding',
    priceCents: 9800,
    quantityAvailable: 5,
    oneoff: false,
    image: '/demo-seed/products/prod-16.svg',
  },
  {
    id: 'seed_prod_017',
    name: 'Custom Pet Portrait Digital',
    description: 'High-resolution custom pet illustration file delivery.',
    type: 'Custom Art',
    category: 'Custom Art',
    priceCents: 7500,
    quantityAvailable: 20,
    oneoff: false,
    image: '/demo-seed/products/prod-17.svg',
  },
  {
    id: 'seed_prod_018',
    name: 'Hand-Painted Skateboard Deck',
    description: 'One-off painted skate deck sealed with matte clear coat.',
    type: 'Art',
    category: 'Art',
    priceCents: 11000,
    quantityAvailable: 3,
    oneoff: true,
    image: '/demo-seed/products/prod-18.svg',
  },
  {
    id: 'seed_prod_019',
    name: 'Clay Plant Marker Set',
    description: 'Set of six stamped ceramic plant markers.',
    type: 'Ceramics',
    category: 'Ceramics',
    priceCents: 2000,
    quantityAvailable: 24,
    oneoff: false,
    image: '/demo-seed/products/prod-19.svg',
  },
  {
    id: 'seed_prod_020',
    name: 'Macrame Wall Hanging',
    description: 'Cotton cord wall hanging with natural oak dowel.',
    type: 'Fiber Art',
    category: 'Fiber Art',
    priceCents: 6800,
    quantityAvailable: 6,
    oneoff: true,
    image: '/demo-seed/products/prod-20.svg',
  },
];

export const seedAdminProducts: Product[] = rows.map((row) => ({
  id: row.id,
  name: row.name,
  description: row.description,
  imageUrls: [row.image],
  imageUrl: row.image,
  type: row.type,
  category: row.category,
  categories: [row.category],
  oneoff: row.oneoff,
  quantityAvailable: row.quantityAvailable,
  visible: true,
  isSold: false,
  priceCents: row.priceCents,
  shippingOverrideEnabled: false,
  shippingOverrideAmountCents: null,
}));
