import type { Product } from '../../lib/types';

const soldAt = [
  '2026-02-25T17:22:00.000Z',
  '2026-02-24T14:08:00.000Z',
  '2026-02-23T19:30:00.000Z',
  '2026-02-22T11:12:00.000Z',
  '2026-02-21T09:45:00.000Z',
  '2026-02-20T21:05:00.000Z',
  '2026-02-19T16:18:00.000Z',
  '2026-02-18T12:50:00.000Z',
  '2026-02-17T10:33:00.000Z',
  '2026-02-16T08:27:00.000Z',
  '2026-02-15T19:09:00.000Z',
  '2026-02-14T13:41:00.000Z',
  '2026-02-13T15:55:00.000Z',
  '2026-02-12T11:26:00.000Z',
  '2026-02-11T18:14:00.000Z',
];

type SoldSeed = {
  id: string;
  name: string;
  description: string;
  type: string;
  priceCents: number;
  soldAt: string;
  image: string;
};

const soldRows: SoldSeed[] = [
  {
    id: 'seed_sold_001',
    name: 'Studio Tee - Midnight Bloom',
    description: 'Limited run screen-printed tee in midnight bloom colorway.',
    type: 'Apparel',
    priceCents: 3400,
    soldAt: soldAt[0],
    image: '/demo-assets/sold/sold-01.svg',
  },
  {
    id: 'seed_sold_002',
    name: 'Embroidered Dad Hat - Rust',
    description: 'Cotton canvas dad hat with custom rust thread embroidery.',
    type: 'Apparel',
    priceCents: 3000,
    soldAt: soldAt[1],
    image: '/demo-assets/sold/sold-02.svg',
  },
  {
    id: 'seed_sold_003',
    name: 'Moon Cat Enamel Pin Set',
    description: 'Collector set of three hard-enamel pins.',
    type: 'Merch',
    priceCents: 2800,
    soldAt: soldAt[2],
    image: '/demo-assets/sold/sold-03.svg',
  },
  {
    id: 'seed_sold_004',
    name: 'Seasonal Sticker Bundle',
    description: 'Twelve weatherproof vinyl stickers in one bundle.',
    type: 'Merch',
    priceCents: 1800,
    soldAt: soldAt[3],
    image: '/demo-assets/sold/sold-04.svg',
  },
  {
    id: 'seed_sold_005',
    name: 'Wildflower Art Print Trio',
    description: 'Three archival 8x10 botanical art prints.',
    type: 'Art Prints',
    priceCents: 5200,
    soldAt: soldAt[4],
    image: '/demo-assets/sold/sold-05.svg',
  },
  {
    id: 'seed_sold_006',
    name: 'Custom Pet Portrait - Digital',
    description: 'One digital pet portrait with two revision rounds.',
    type: 'Custom Art',
    priceCents: 9000,
    soldAt: soldAt[5],
    image: '/demo-assets/sold/sold-06.svg',
  },
  {
    id: 'seed_sold_007',
    name: 'Speckled Stoneware Mug Pair',
    description: 'Wheel-thrown mug pair with food-safe glaze.',
    type: 'Ceramics',
    priceCents: 7200,
    soldAt: soldAt[6],
    image: '/demo-assets/sold/sold-07.svg',
  },
  {
    id: 'seed_sold_008',
    name: 'Sage + Cedar Candle Duo',
    description: 'Two 8oz soy candles with gift wrap.',
    type: 'Candles',
    priceCents: 4600,
    soldAt: soldAt[7],
    image: '/demo-assets/sold/sold-08.svg',
  },
  {
    id: 'seed_sold_009',
    name: 'Sterling Fern Necklace',
    description: 'Hand-fabricated sterling fern pendant on 18 inch chain.',
    type: 'Jewelry',
    priceCents: 5800,
    soldAt: soldAt[8],
    image: '/demo-assets/sold/sold-09.svg',
  },
  {
    id: 'seed_sold_010',
    name: 'Walnut Coaster Gift Set',
    description: 'Hand-oiled walnut coaster set with felt-lined box.',
    type: 'Wood Goods',
    priceCents: 4200,
    soldAt: soldAt[9],
    image: '/demo-assets/sold/sold-10.svg',
  },
  {
    id: 'seed_sold_011',
    name: 'Maple Serving Board',
    description: 'Small-batch maple serving board with rounded handle.',
    type: 'Wood Goods',
    priceCents: 6400,
    soldAt: soldAt[10],
    image: '/demo-assets/sold/sold-11.svg',
  },
  {
    id: 'seed_sold_012',
    name: 'Hand-Stitched Card Wallet',
    description: 'Vegetable-tanned wallet with hand-stitched seam.',
    type: 'Leather Goods',
    priceCents: 5000,
    soldAt: soldAt[11],
    image: '/demo-assets/sold/sold-12.svg',
  },
  {
    id: 'seed_sold_013',
    name: 'Crochet Bee Plush + Beanie',
    description: 'Matching plush and beanie set, gift ready.',
    type: 'Crochet',
    priceCents: 6800,
    soldAt: soldAt[12],
    image: '/demo-assets/sold/sold-13.svg',
  },
  {
    id: 'seed_sold_014',
    name: 'Letterpress Thank You Kit',
    description: 'Thirty custom thank-you cards and envelopes.',
    type: 'Stationery',
    priceCents: 5400,
    soldAt: soldAt[13],
    image: '/demo-assets/sold/sold-14.svg',
  },
  {
    id: 'seed_sold_015',
    name: 'Hand-Painted Deck Commission',
    description: 'Commissioned skateboard deck with abstract landscape art.',
    type: 'Art',
    priceCents: 12800,
    soldAt: soldAt[14],
    image: '/demo-assets/sold/sold-15.svg',
  },
];

export const seedSoldProducts: Product[] = soldRows.map((row) => ({
  id: row.id,
  name: row.name,
  description: row.description,
  imageUrls: [row.image],
  imageUrl: row.image,
  type: row.type,
  category: row.type,
  categories: [row.type],
  oneoff: true,
  quantityAvailable: 0,
  visible: false,
  isSold: true,
  priceCents: row.priceCents,
  soldAt: row.soldAt,
}));

